markdown: rdiscount
permalink: /:year/:month/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Hasan Ozgan
url: http://www.hasanozgan.com
description: Internet Stratejileri Mimarileri ve Teknolojileri Üzerine
twitter: HasanOzgan
github: HasanOzgan
linkedin: hasanozgan

google:
    tracking_id: 'UA-1491715-5'
